In [8]:
import pandas as pd
import numpy as np

In [9]:
def loadDataSet(fileName):
    numFeat=len(open(fileName).readline().split('\t'))-1
    dataMat=[]
    labelMat=[]
    fr=open(fileName)
    for line in fr.readlines():
        lineArr=[]
        curLine=line.strip().split('\t')
        for i in range(numFeat):
            lineArr.append(float(curLine[i]))
        dataMat.append(lineArr)
        labelMat.append(float(curLine[-1]))
    return dataMat,labelMat

In [10]:
def standRegres(xArr,yArr):
    xMat=np.mat(xArr)
    yMat=np.mat(yArr).T
    xTx=xMat.T*xMat
    if np.linalg.det(xTx)==0.0:
        print('error')
        return
    ws=xTx.I*(xMat.T*yMat)
    return ws

In [11]:
xArr,yArr=loadDataSet('ex0.txt')
ws=standRegres(xArr,yArr)
ws

matrix([[ 3.00774324],
        [ 1.69532264]])

In [12]:
xMat=np.mat(xArr)
yMat=np.mat(yArr)
yHat=xMat*ws

In [13]:
yHat

matrix([[ 3.12257084],
        [ 3.73301922],
        [ 4.69582855],
        [ 4.25946098],
        [ 4.67099547],
        [ 3.89977285],
        [ 3.65007895],
        [ 3.06514517],
        [ 3.23286683],
        [ 3.24221654],
        [ 3.42785945],
        [ 4.10677005],
        [ 4.24737842],
        [ 3.40925159],
        [ 4.6518468 ],
        [ 4.03763819],
        [ 3.61572324],
        [ 3.25838991],
        [ 4.08905393],
        [ 3.39829811],
        [ 3.12681762],
        [ 3.12159094],
        [ 4.57689489],
        [ 4.22453225],
        [ 3.03380205],
        [ 3.575795  ],
        [ 3.07638008],
        [ 3.36812645],
        [ 4.05412689],
        [ 3.92524508],
        [ 3.08463121],
        [ 3.22264573],
        [ 3.95116656],
        [ 4.53547307],
        [ 4.63266931],
        [ 3.47321272],
        [ 3.67637171],
        [ 4.48687834],
        [ 3.70271024],
        [ 4.54873897],
        [ 3.29055527],
        [ 4.13515992],
        [ 3.4548456 ],
        [ 3

In [76]:
import matplotlib.pyplot as plt
fig=plt.figure()
ax=fig.add_subplot(111)
ax.scatter(xMat[:,1].flatten().A[0],yMat.T[:,0].flatten().A[0])
xCopy=xMat.copy()
xCopy.sort(0)
yHat=xCopy*ws
ax.plot(xCopy[:,1],yHat)
plt.show()

# 加权线性回归

In [72]:
def lwlr(testPoint,xArr,yArr,k=1.0):
    xMat=np.mat(xArr)
    yMat=np.mat(yArr).T
    m=np.shape(xMat)[0]
    weights=np.mat(np.eye((m)))
    for j in range(m):
        diffMat=testPoint-xMat[j,:]
        weights[j,j]=np.exp(diffMat*diffMat.T/(-2.0*k**2))
    xTx=xMat.T*(weights*xMat)
    if np.linalg.det(xTx)==0.0:
        print("error")
        return
    ws=xTx.I*(xMat.T*(weights*yMat))
    return testPoint*ws

In [73]:
def lwlrTest(testArr,xArr,yArr,k=1.0):
    m=np.shape(testArr)[0]
    yHat=np.zeros(m)
    for i in range(m):
        yHat[i]=lwlr(testArr[i],xArr,yArr,k)
    return yHat

In [74]:
xArr,yArr=loadDataSet('ex0.txt')
lwlr(xArr[0],xArr,yArr,0.001)

[[ 0.  0.]] [1.0, 0.067732] [[ 1.        0.067732]]
*****
[[ 0.       -0.360078]] [1.0, 0.067732] [[ 1.       0.42781]]
*****
[[ 0.       -0.927999]] [1.0, 0.067732] [[ 1.        0.995731]]
*****
[[ 0.       -0.670604]] [1.0, 0.067732] [[ 1.        0.738336]]
*****
[[ 0.       -0.913351]] [1.0, 0.067732] [[ 1.        0.981083]]
*****
[[ 0.       -0.458439]] [1.0, 0.067732] [[ 1.        0.526171]]
*****
[[ 0.       -0.311155]] [1.0, 0.067732] [[ 1.        0.378887]]
*****
[[ 0.        0.033873]] [1.0, 0.067732] [[ 1.        0.033859]]
*****
[[ 0.       -0.065059]] [1.0, 0.067732] [[ 1.        0.132791]]
*****
[[ 0.       -0.070574]] [1.0, 0.067732] [[ 1.        0.138306]]
*****
[[ 0.       -0.180077]] [1.0, 0.067732] [[ 1.        0.247809]]
*****
[[ 0.       -0.580538]] [1.0, 0.067732] [[ 1.       0.64827]]
*****
[[ 0.       -0.663477]] [1.0, 0.067732] [[ 1.        0.731209]]
*****
[[ 0.       -0.169101]] [1.0, 0.067732] [[ 1.        0.236833]]
*****
[[ 0.       -0.902056]] [1.0, 0.0677

matrix([[ 3.20175729]])

In [60]:
yHat=lwlrTest(xArr,xArr,yArr,0.003)

In [61]:
xMat=np.mat(xArr)
srtInd=xMat[:,1].argsort(0)
xSort=xMat[srtInd][:,0,:]

In [62]:
import matplotlib.pyplot as plt
fig=plt.figure()
ax=fig.add_subplot(111)
ax.plot(xSort[:,1],yHat[srtInd])
ax.scatter(xMat[:,1].flatten().A[0],np.mat(yArr).T.flatten().A[0],s=2,c='red')
plt.show()